SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

CAR_WIDTH = 50
CAR_HEIGHT = 100
CAR_START_X = (SCREEN_WIDTH - CAR_WIDTH) // 2
CAR_START_Y = SCREEN_HEIGHT - CAR_HEIGHT - 10

OBSTACLE_WIDTH = 50
OBSTACLE_HEIGHT = 50
OBSTACLE_MIN_SPEED = 1
OBSTACLE_MAX_SPEED = 5

GAME_SPEED = 60
